export { default as userController } from './user.controller'
export { default as tripController } from './trip.controller'
export { default as seatController } from './seat.controller'
export { default as bookingController } from './booking.controller'
export { default as paymentController } from './payment.controller'
